server:
  port: 8082

spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: auth-service-group
      auto-offset-reset: earliest

    admin:
      auto-create: true
      properties:
        default.replication.factor: 1
        default.partitions: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  url: http://localhost:8083
  realm: biblioteca-dev
  admin-user: admin-bib
  admin-pass: admin
  client-id: biblioteca-dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
