version: "3.9"

services:

  # ============================
  # INFRAESTRUCTURA
  # ============================

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: academia
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-productdb:
    image: postgres:15
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contra
    ports:
      - "5433:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
      - ./init-productdb.sql:/docker-entrypoint-initdb.d/init-productdb.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
      - postgres-productdb
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  # ============================
  # MICROSERVICIOS
  # ============================

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - kafka

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
      - keycloak
      - eureka-server

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
      - eureka-server

  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-productdb

  api-gateway:
    build: ./api-gateway
    ports:
      - "8084:8080"
    depends_on:
      - auth-service
      - user-service
      - product-service
      - eureka-server

volumes:
  postgres_data:
  postgres_product_data:
  pgadmin_data:
  keycloak_data:
  kafka_data:
  zookeeper_data:
  zookeeper_log:
