version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contra
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./product_service_schema.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
