spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
